import type { FastifyRequest, FastifyReply } from 'fastify';
import { AuthService } from '../services/auth.service';
import { successResponse, errorResponse } from '../utils/response';
import { env } from '../config/env';
import '@fastify/cookie';
import '@fastify/jwt';

/**
 * GET /api/v1/auth/google/callback
 * Google redirects here after successful auth. We fetch the token, get the profile, sync user, set a cookie and redirect.
 */
export const googleCallback = async (request: FastifyRequest, reply: FastifyReply) => {
  try {
    // Exchange auth code for access token via fastify-oauth2 on the server instance
    const oauth2 = (request.server as any).googleOAuth2;
    const { token } = await oauth2.getAccessTokenFromAuthorizationCodeFlow(request);

    // Fetch user profile from Google using native fetch
    const profileResponse = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
      headers: { Authorization: `Bearer ${token.access_token}` },
    });
    const profile = await profileResponse.json() as any;

    // Sync user into db
    const user = await AuthService.syncUser({
      id: profile.id,
      email: profile.email,
      name: profile.name,
      avatarUrl: profile.picture,
      provider: 'google',
    });

    // Create our own JWT payload
    const jwtPayload = {
      id: user.id,
      email: user.email,
    };
    
    // Sign token
    const signedToken = await reply.jwtSign(jwtPayload);

    // Set HTTP-only cookie
    reply.setCookie('token', signedToken, {
      domain: 'localhost',
      path: '/',
      secure: env.IS_PRODUCTION,
      httpOnly: true,
      sameSite: 'lax',
      maxAge: 60 * 60 * 24 * 7, // 7 days
    });

    // Redirect to frontend dashboard
    return reply.redirect(`${env.FRONTEND_URL}/dashboard`);
  } catch (error) {
    request.log.error(error, 'Google auth callback failed');
    return reply.redirect(`${env.FRONTEND_URL}/login?error=auth_failed`);
  }
};

/**
 * GET /api/v1/auth/me
 * Returns the currently authenticated user's profile.
 */
export const getMe = async (request: FastifyRequest, reply: FastifyReply) => {
  try {
    const authUser = request.user as any;

    if (!authUser?.email) {
      return reply.code(401).send(
        errorResponse('Not authenticated', 401)
      );
    }

    const user = await AuthService.getUserByEmail(authUser.email);

    if (!user) {
      return reply.code(404).send(
        errorResponse('User not found', 404)
      );
    }

    return reply.status(200).send(
      successResponse({ user }, 'User profile retrieved')
    );
  } catch (error) {
    request.log.error(error, 'Get me failed');
    return reply.status(500).send(
      errorResponse('Failed to get user profile', 500, error)
    );
  }
};

/**
 * POST /api/v1/auth/logout
 * Server-side logout acknowledgment. Clears the session cookie.
 */
export const logout = async (_request: FastifyRequest, reply: FastifyReply) => {
  // Clear the JWT login cookie using the exact same domain/path parameters
  reply.clearCookie('token', { 
    domain: 'localhost', 
    path: '/' 
  });

  // Clear the OAuth2 state cookie generated by fastify-oauth2
  reply.clearCookie('oauth2-redirect-state', {
    path: '/' // Fastify-oauth2 usually sets it at the root path
  });
  
  return reply.status(200).send(
    successResponse(null, 'Logged out successfully')
  );
};
